#!/usr/bin/env python3
"""SO-101 gripper -- fixed jaw (wrist roll follower) + moving jaw, generated by script.

Blender is not parametric CAD, so the only way this part stays modifiable is for
the *script* to be the source and the mesh to be a build artifact.  Nothing here
is hand-modelled: re-running this file regenerates both parts, the assembly, the
render, the STLs and the .blend from the PARAMETERS block below.

    /Applications/Blender.app/Contents/MacOS/Blender --background \
        --python cad/blender/so101_gripper.py -- --out cad/blender/out

Override any parameter without editing the file:

    ... --python so101_gripper.py -- --set jaw_open_deg=0 --set mj_finger_length=120

Every dimension below is measured from the reference STEP files at
cad/build123d/reference/ -- see MEASUREMENTS.md for the number, the STEP entity
it came from, and how it was read.  Nothing is eyeballed off a mesh.
Context for why this part matters: plans/hand_1_0.md (section 2, "the gripper")
and plans/gripper_bet.md (Hand 1.0 is the baseline the bet is measured against).
"""

# ======================================================================
# PARAMETERS -- the only place geometry is decided.  mm and degrees.
# ======================================================================
P = dict(

    # ---- what Jake is most likely to change for the Hand 1.0 paper gripper ----
    jaw_open_deg           = 25.0,   # 0 = fingertips touching; opens about the pivot
    mj_finger_length       = 82.0,   # pivot axis -> moving fingertip
    fixed_finger_length    = 81.03,  # pivot axis -> fixed fingertip, along Z
    fingertip_thickness    = 6.0,    # material thickness at the very tip of each finger
    grip_face_inset        = 5.0,    # pad-hole line, measured in from the gripping face
    pad_hole_d             = 1.5,    # grip-insert holes on both gripping faces
    mj_pad_hole_pitch      = 9.944,  # moving jaw, hole-to-hole
    fin_pad_hole_pitch     = 10.0,   # fixed jaw, hole-to-hole
    pad_hole_count         = 5,
    wall_thickness         = 2.2,    # servo-cradle side walls
    base_plate_thickness   = 10.0,   # wrist-roll mounting plate

    # ---- fasteners and the servo horn interface (bought parts: do not invent) ----
    m3_clearance_d         = 3.2,    # every M3 hole in both parts
    m3_counterbore_d       = 5.4,    # moving jaw
    m3_counterbore_d_body  = 6.0,    # fixed jaw, under the wrist plate
    m2_clearance_d         = 2.0,    # servo case screws
    m2_counterbore_d       = 4.0,
    horn_bolt_offset       = 4.95,   # 4 screws on a 9.9 mm square -> 14.0 mm PCD
    servo_horn_bore        = 6.0,    # central bore through the moving jaw hub
    wrist_bore_d           = 5.4,    # central bore through the wrist-roll plate
    horn_pocket_d          = 20.0,   # recess the servo horn drops into
    horn_pocket_depth      = 6.5,    # drive side
    bearing_pocket_depth   = 3.6,    # idler side
    horn_boss_height       = 1.5,    # raised ring on each inner fork face
    edge_break             = 0.75,   # edge fillet on every printed edge

    # ---- moving jaw ----
    mj_hub_r               = 10.0,   # hub radius about the pivot axis
    mj_hub_span            = 48.0,   # outside face to outside face of the fork
    mj_fork_gap            = 33.4,   # between the fork's inner faces
    mj_fork_gap_offset     = -0.7,   # fork gap is not centred on the pivot plane
    mj_arm_root            = 18.0,   # where the fork slot ends and the finger begins
    mj_back_x              = -12.3,  # back of the finger at the root
    mj_grip_face_x         = 10.06,  # gripping face at the pivot plane
    mj_grip_face_deg       = 6.03,   # gripping face tilt (face closes on the fixed jaw)
    mj_root_width          = 40.8,   # fork-axis width of the finger at its root
    mj_tip_width           = 12.0,   # fork-axis width at the fingertip
    mj_closed_lean_deg     = 8.84,   # finger lean from vertical when the tips touch

    # ---- fixed jaw / wrist roll follower ----
    body_x_min             = -35.2,
    body_x_max             = 30.0,
    body_y_min             = -24.218,
    body_y_max             = 27.782,
    base_corner_r          = 10.0,
    wrist_centre_y         = -0.218, # wrist-roll axis is not on the part centreline
    wrist_boss_d           = 24.0,
    wrist_boss_height      = 6.0,
    wrist_chamfer          = 0.8,
    cradle_half_width      = 16.0,   # inner face of each servo-cradle wall
    cradle_x_min           = -16.0,
    cradle_top_z           = 38.0,
    servo_screw_pitch_z    = 20.5,   # the servo's own case screws
    servo_screw_x_py       = -12.6,
    servo_screw_x_ny       = -8.8,
    access_bore_d          = 10.0,   # lightening / cable bore through the fin root
    fin_lean_deg           = 20.0,   # fixed finger's lean from vertical
    fin_pivot_to_face      = 15.82,  # pivot axis -> fixed gripping face
    fin_tip_s              = 80.44,  # gripping-face length, pivot station to tip
    fin_root_thickness     = 26.0,   # in from the gripping face, at the pivot station
    fin_thickness_at_24    = 16.7,
    fin_pad_first_s        = 24.14,  # first pad hole, measured along the finger
    pivot_x                = -25.54, # gripper servo output axis, in the body frame
    pivot_z                = 24.35,

    # ---- measured width tables (fork-axis width of each finger) ----------
    # moving jaw: (distance from pivot along the finger, width across the fork axis)
    mj_width_table = [(0.0, 48.0), (18.0, 40.8), (28.8, 20.4), (38.8, 17.8),
                      (48.7, 16.2), (58.7, 14.9), (72.0, 13.2), (82.0, 6.0)],
    # fixed jaw: (Z height above the wrist face, width across Y)
    fin_width_table = [(36.0, 32.0), (42.0, 29.3), (47.0, 24.5), (52.0, 21.5),
                       (57.0, 19.6), (62.0, 18.3), (67.0, 17.3), (72.0, 16.6),
                       (77.0, 15.8), (82.0, 15.2), (87.0, 14.4), (92.0, 13.3),
                       (97.0, 11.9), (102.0, 9.4), (105.375, 2.83)],

    # ---- output ----
    render_px              = 1200,
    stl_ascii              = False,
)
# ======================================================================
# END PARAMETERS
# ======================================================================

import math
import os
import sys

import bpy
import bmesh
import mathutils


# ---------------------------------------------------------------- plumbing
def parse_args(argv):
    args = argv[argv.index("--") + 1:] if "--" in argv else []
    out = "out"
    i = 0
    while i < len(args):
        if args[i] == "--set":
            k, _, v = args[i + 1].partition("=")
            if k not in P:
                raise SystemExit(f"unknown parameter: {k}")
            P[k] = type(P[k])(v) if not isinstance(P[k], list) else eval(v)
            i += 2
        elif args[i] == "--out":
            out = args[i + 1]
            i += 2
        else:
            i += 1
    return out


def reset():
    bpy.ops.wm.read_factory_settings(use_empty=True)


def mesh_from(name, verts, faces):
    me = bpy.data.meshes.new(name)
    me.from_pydata(verts, [], faces)
    me.validate()
    ob = bpy.data.objects.new(name, me)
    bpy.context.scene.collection.objects.link(ob)
    return ob


def loft(name, rings, cap_start=True, cap_end=True):
    """Skin a list of equal-length closed rings of 3D points."""
    n = len(rings[0])
    verts, faces = [], []
    for r in rings:
        assert len(r) == n
        verts.extend(r)
    for k in range(len(rings) - 1):
        a, b = k * n, (k + 1) * n
        for i in range(n):
            j = (i + 1) % n
            faces.append([a + i, a + j, b + j, b + i])
    if cap_start:
        faces.append(list(range(n - 1, -1, -1)))
    if cap_end:
        base = (len(rings) - 1) * n
        faces.append([base + i for i in range(n)])
    return mesh_from(name, verts, faces)


def rounded_rect(w, h, r, seg=6):
    """2D closed ring, counter-clockwise, centred on the origin."""
    r = min(r, w / 2, h / 2)
    hw, hh = w / 2 - r, h / 2 - r
    pts = []
    for cx, cy, a0 in ((hw, hh, 0.0), (-hw, hh, 90.0),
                       (-hw, -hh, 180.0), (hw, -hh, 270.0)):
        for k in range(seg + 1):
            a = math.radians(a0 + 90.0 * k / seg)
            pts.append((cx + r * math.cos(a), cy + r * math.sin(a)))
    return pts


def cylinder(name, d, z0, z1, centre=(0.0, 0.0), seg=48, axis="Z"):
    r = d / 2.0
    rings = []
    for z in (z0, z1):
        ring = []
        for i in range(seg):
            a = 2 * math.pi * i / seg
            u, v = centre[0] + r * math.cos(a), centre[1] + r * math.sin(a)
            ring.append({"Z": (u, v, z), "Y": (u, z, v), "X": (z, u, v)}[axis])
        rings.append(ring)
    return loft(name, rings)


def cone(name, d0, d1, z0, z1, centre=(0.0, 0.0), seg=48, axis="Z"):
    rings = []
    for d, z in ((d0, z0), (d1, z1)):
        r = d / 2.0
        ring = []
        for i in range(seg):
            a = 2 * math.pi * i / seg
            u, v = centre[0] + r * math.cos(a), centre[1] + r * math.sin(a)
            ring.append({"Z": (u, v, z), "Y": (u, z, v), "X": (z, u, v)}[axis])
        rings.append(ring)
    return loft(name, rings)


def box(name, x0, x1, y0, y1, z0, z1):
    v = [(x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0),
         (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)]
    f = [[3, 2, 1, 0], [4, 5, 6, 7], [0, 1, 5, 4],
         [1, 2, 6, 5], [2, 3, 7, 6], [3, 0, 4, 7]]
    return mesh_from(name, v, f)


def boolean(target, tool, op="DIFFERENCE"):
    m = target.modifiers.new("bool", "BOOLEAN")
    m.operation = op
    m.object = tool
    m.solver = "EXACT"
    bpy.context.view_layer.objects.active = target
    bpy.ops.object.modifier_apply(modifier=m.name)
    bpy.data.objects.remove(tool, do_unlink=True)
    return target


def bevel(ob, width):
    m = ob.modifiers.new("break", "BEVEL")
    m.width = width
    m.segments = 2
    m.limit_method = "ANGLE"
    m.angle_limit = math.radians(35)
    m.harden_normals = False
    bpy.context.view_layer.objects.active = ob
    bpy.ops.object.modifier_apply(modifier=m.name)
    for pol in ob.data.polygons:
        pol.use_smooth = False
    return ob


def interp(table, x):
    if x <= table[0][0]:
        return table[0][1]
    if x >= table[-1][0]:
        return table[-1][1]
    for (a, va), (b, vb) in zip(table, table[1:]):
        if a <= x <= b:
            return va + (vb - va) * (x - a) / (b - a)
    return table[-1][1]


# ---------------------------------------------------------------- moving jaw
def build_moving_jaw():
    """Built in its own frame: pivot at the origin, finger along -Y, fork along Z.

    +X is the gripping side.  This is the frame the reference STEP file uses,
    so every number below can be checked against MEASUREMENTS.md directly.
    """
    half = P["mj_hub_span"] / 2.0
    face_slope = math.tan(math.radians(P["mj_grip_face_deg"]))

    def face_x(y):                      # gripping face, tilted by mj_grip_face_deg
        return P["mj_grip_face_x"] + face_slope * y

    # --- hub: a disc about the pivot, full fork width -------------------
    hub = cylinder("mj_hub", 2 * P["mj_hub_r"], -half, half, seg=64)

    # --- finger: lofted rectangles from the hub out to the tip ----------
    rings = []
    stations = [0.0, 6.0, 12.0, P["mj_arm_root"], 28.8, 38.8, 48.7, 58.7,
                72.0, P["mj_finger_length"]]
    for s in stations:
        y = -s
        w = interp(P["mj_width_table"], s)          # width along the fork axis
        xf = face_x(y)
        # back of the finger tapers from the hub to the fingertip thickness
        depth = (P["mj_grip_face_x"] - P["mj_back_x"]) * (1 - s / P["mj_finger_length"]) \
            + P["fingertip_thickness"] * (s / P["mj_finger_length"])
        xb = xf - depth
        r = min(2.0, w / 2.5, depth / 2.5)
        ring = [((xb + xf) / 2 + u, y, v) for (u, v) in rounded_rect(depth, w, r)]
        rings.append(ring)
    finger = loft("mj_finger", rings)
    boolean(hub, finger, "UNION")

    # --- trim to the gripping plane and the flat back -------------------
    big = 200.0
    cut = box("cut_face", 0, big, -big, big, -big, big)
    bm = bmesh.new()
    bm.from_mesh(cut.data)
    for v in bm.verts:                              # shear so x=0 becomes the face
        v.co.x += face_x(v.co.y)
    bm.to_mesh(cut.data)
    bm.free()
    boolean(hub, cut)

    # --- fork slot ------------------------------------------------------
    g0 = P["mj_fork_gap_offset"] - P["mj_fork_gap"] / 2.0
    g1 = P["mj_fork_gap_offset"] + P["mj_fork_gap"] / 2.0
    boolean(hub, box("slot", -big, big, -P["mj_arm_root"], big, g0, g1))

    # --- raised pivot bosses on the inner fork faces --------------------
    for z0, z1 in ((g0, g0 + P["horn_boss_height"]),
                   (g1 - P["horn_boss_height"], g1)):
        boolean(hub, cylinder("boss", P["horn_pocket_d"], z0, z1), "UNION")

    # --- horn pocket (drive side) and bearing pocket (idler side) -------
    boolean(hub, cylinder("pocket_a", P["horn_pocket_d"],
                          half - P["horn_pocket_depth"], half + 1))
    boolean(hub, cylinder("pocket_b", P["horn_pocket_d"],
                          -half - 1, -half + P["bearing_pocket_depth"]))

    # --- central bore + countersinks ------------------------------------
    boolean(hub, cylinder("bore", P["servo_horn_bore"], -half - 1, half + 1))
    cs = P["servo_horn_bore"]
    boolean(hub, cone("cs_a", cs, 2 * cs, half - P["horn_pocket_depth"],
                      half - P["horn_pocket_depth"] + cs / 2))
    boolean(hub, cone("cs_b", 2 * cs, cs, -half + P["bearing_pocket_depth"] - cs / 2,
                      -half + P["bearing_pocket_depth"]))

    # --- 4 horn screws, through both arms, counterbored on the inside ----
    o = P["horn_bolt_offset"]
    for sx in (-1, 1):
        for sy in (-1, 1):
            c = (sx * o, sy * o)
            boolean(hub, cylinder("scr", P["m3_clearance_d"], -half - 1, half + 1, c))
            boolean(hub, cylinder("cb_a", P["m3_counterbore_d"],
                                  g1 - 3.0, g1 + 0.01, c))
            boolean(hub, cylinder("cb_b", P["m3_counterbore_d"],
                                  g0 - 0.01, g0 + 3.0, c))

    # --- grip-insert holes, grip_face_inset in from the gripping face ----
    for k in range(P["pad_hole_count"]):
        y = -(P["mj_arm_root"] + 0.887) - k * P["mj_pad_hole_pitch"]
        x = face_x(y) - P["grip_face_inset"]
        boolean(hub, cylinder("pad", P["pad_hole_d"], -half - 1, half + 1, (x, y)))

    hub.name = "moving_jaw"
    hub.data.name = "moving_jaw"
    bevel(hub, P["edge_break"])
    return hub


# ---------------------------------------------------------------- fixed jaw
def build_fixed_jaw():
    """Built in the body frame: wrist-roll face at z=0, fin rising in +Z."""
    cy = P["wrist_centre_y"]
    big = 300.0
    z_plate = P["base_plate_thickness"]

    # --- base plate -----------------------------------------------------
    w = P["body_x_max"] - P["body_x_min"]
    h = P["body_y_max"] - P["body_y_min"]
    mx = (P["body_x_max"] + P["body_x_min"]) / 2.0
    my = (P["body_y_max"] + P["body_y_min"]) / 2.0
    prof = rounded_rect(w, h, P["base_corner_r"], seg=8)
    rings = [[(mx + u, my + v, z) for (u, v) in prof] for z in (0.0, z_plate)]
    body = loft("fixed_jaw", rings)

    # --- wrist-roll horn pocket: Ø24 x 6 recess in the underside --------
    # The reference part's bottom face is at z = -0.05, so this is a pocket the
    # wrist-roll servo horn drops into, not a protruding spigot.
    ch = P["wrist_chamfer"]
    boolean(body, cone("pocket_ch", P["wrist_boss_d"] + 2 * ch, P["wrist_boss_d"],
                       -1.0, ch, (0.0, cy)))
    boolean(body, cylinder("horn_pocket", P["wrist_boss_d"],
                           -1.0, P["wrist_boss_height"], (0.0, cy)))
    boolean(body, cylinder("wrist_bore", P["wrist_bore_d"],
                           -1.0, z_plate + 1, (0.0, cy)))
    o = P["horn_bolt_offset"]
    for sx in (-1, 1):
        for sy in (-1, 1):
            c = (sx * o, cy + sy * o)
            boolean(body, cylinder("hs", P["m3_clearance_d"],
                                   -1.0, z_plate + 1, c))
            boolean(body, cylinder("hcb", P["m3_counterbore_d_body"],
                                   z_plate - 3.0, z_plate + 1, c))

    # --- servo cradle: two walls plus a back wall -----------------------
    t = P["wall_thickness"]
    for s in (-1, 1):
        y0 = cy + s * P["cradle_half_width"]
        boolean(body, box("wall", P["cradle_x_min"], P["body_x_max"] - 3.0,
                          min(y0, y0 + s * t), max(y0, y0 + s * t),
                          z_plate, P["cradle_top_z"]), "UNION")
    boolean(body, box("back", P["body_x_max"] - 3.0 - t, P["body_x_max"] - 3.0,
                      cy - P["cradle_half_width"], cy + P["cradle_half_width"],
                      z_plate, P["cradle_top_z"]), "UNION")

    # --- the servo's own case screws ------------------------------------
    for zc in (P["pivot_z"] - P["servo_screw_pitch_z"] / 2,
               P["pivot_z"] + P["servo_screw_pitch_z"] / 2):
        for s, xs in ((1, P["servo_screw_x_py"]), (-1, P["servo_screw_x_ny"])):
            y0 = cy + s * (P["cradle_half_width"] + t + 1)
            y1 = cy + s * (P["cradle_half_width"] - 1)
            boolean(body, cylinder("ss", P["m2_clearance_d"],
                                   min(y0, y1), max(y0, y1), (xs, zc), axis="Y"))
            yc = cy + s * (P["cradle_half_width"] + t)
            boolean(body, cylinder("scb", P["m2_counterbore_d"],
                                   min(yc, yc - s * 1.2), max(yc, yc - s * 1.2),
                                   (xs, zc), axis="Y"))

    # --- the fin -------------------------------------------------------
    # (s, t) frame: s runs up the gripping face from the pivot station, t is the
    # distance in from that face.  The pivot axis sits fin_pivot_to_face behind
    # the face, which is what makes the fixed finger's tip land on the face.
    lean = math.radians(P["fin_lean_deg"])
    u = mathutils.Vector((math.sin(lean), 0.0, math.cos(lean)))     # up the fin
    n = mathutils.Vector((math.cos(lean), 0.0, -math.sin(lean)))    # in from the face
    pivot = mathutils.Vector((P["pivot_x"], 0.0, P["pivot_z"]))
    face0 = pivot - n * P["fin_pivot_to_face"]      # origin of the gripping face
    s_tip = P["fin_tip_s"]

    thick = [(-20.0, P["fin_root_thickness"] + 4.0),
             (0.0, P["fin_root_thickness"]),
             (24.0, P["fin_thickness_at_24"]),
             (s_tip - 8.0, P["fingertip_thickness"]),
             (s_tip, 2.0)]
    rings = []
    for st in [-20.0, -10.0, 0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0,
               s_tip - 8.0, s_tip - 3.0, s_tip]:
        c = face0 + u * st
        d = interp(thick, st)
        wy = interp(P["fin_width_table"], c.z)
        r = min(2.0, wy / 2.5, d / 2.5)
        ring = []
        for (a, b) in rounded_rect(d, wy, r):       # a: across t, b: across Y
            pt = c + n * (a + d / 2.0)
            ring.append((pt.x, b, pt.z))
        rings.append(ring)
    boolean(body, loft("fin", rings), "UNION")

    # the gripping face runs outboard of the body below z~44, so the real part
    # stops at its own -X wall; trim the fin to the measured envelope.
    boolean(body, box("envelope", P["body_x_min"], P["body_x_max"] + 50,
                      -big, big, -big, big), "INTERSECT")

    # --- lightening / cable bore through the fin root -------------------
    boolean(body, cylinder("access", P["access_bore_d"],
                           P["body_x_min"] - 1, P["cradle_x_min"] + 1,
                           (0.132, P["pivot_z"]), axis="X"))

    # --- grip-insert holes on the fixed gripping face -------------------
    for k in range(P["pad_hole_count"]):
        st = P["fin_pad_first_s"] + k * P["fin_pad_hole_pitch"]
        c = face0 + u * st + n * P["grip_face_inset"]
        boolean(body, cylinder("pad", P["pad_hole_d"], -big, big,
                               (c.x, c.z), axis="Y"))

    body.name = "fixed_jaw"
    body.data.name = "fixed_jaw"
    bevel(body, P["edge_break"])
    return body


# ---------------------------------------------------------------- assembly
def place_moving_jaw(jaw):
    """Put the moving jaw on the pivot and swing it open by jaw_open_deg.

    At jaw_open_deg = 0 the two fingertips touch; the SO-101's jaws swing on an
    arc, so the gripping faces meet at the tips and not flat (plans/hand_1_0.md
    calls this out as the reason Hand 1.0 wants a parallel linkage instead).
    """
    lean = math.radians(P["mj_closed_lean_deg"] - P["jaw_open_deg"])
    # jaw local: +X grips, -Y is the finger, Z is the fork axis.
    # body: finger up (+Z), leaning +X by `lean`; fork along Y.
    rot = (mathutils.Matrix.Rotation(lean, 4, "Y")
           @ mathutils.Euler((-math.pi / 2, 0.0, 0.0), "XYZ").to_matrix().to_4x4())
    jaw.matrix_world = mathutils.Matrix.Translation(
        (P["pivot_x"], P["wrist_centre_y"], P["pivot_z"])) @ rot
    return jaw


def tip_gap():
    return 2.0 * P["mj_finger_length"] * math.sin(math.radians(P["jaw_open_deg"]) / 2)


# ---------------------------------------------------------------- output
def export_stl(objs, path):
    for ob in bpy.context.scene.objects:
        ob.select_set(ob in objs)
    bpy.context.view_layer.objects.active = objs[0]
    bpy.ops.wm.stl_export(filepath=path, export_selected_objects=True,
                          ascii_format=P["stl_ascii"], apply_modifiers=True)


def render(path, rot, objs, margin=1.12):
    """Ortho render from a direction, auto-framed on the given objects."""
    sc = bpy.context.scene
    sc.render.engine = "BLENDER_WORKBENCH"
    sc.render.resolution_x = sc.render.resolution_y = P["render_px"]
    sc.render.film_transparent = False
    sh = sc.display.shading
    sh.light = "STUDIO"
    sh.studio_light = "Default"
    sh.color_type = "OBJECT"
    sh.show_cavity = True
    sh.cavity_type = "BOTH"
    sh.curvature_ridge_factor = 1.0
    sh.curvature_valley_factor = 1.0
    sh.show_object_outline = True
    sh.show_shadows = True
    sh.background_type = "VIEWPORT"
    sh.background_color = (0.93, 0.93, 0.94)
    sc.display.render_aa = "16"
    sc.render.image_settings.file_format = "PNG"
    sc.render.image_settings.color_mode = "RGB"
    sc.render.image_settings.compression = 100

    cam = sc.camera
    if cam is None:
        cd = bpy.data.cameras.new("cam")
        cd.type = "ORTHO"
        cam = bpy.data.objects.new("cam", cd)
        sc.collection.objects.link(cam)
        sc.camera = cam
    cam.rotation_euler = rot

    # auto-frame: project every bbox corner into the camera's own axes
    basis = mathutils.Euler(rot, "XYZ").to_matrix()
    right, up, back = basis.col[0], basis.col[1], basis.col[2]
    pts = [ob.matrix_world @ mathutils.Vector(c)
           for ob in objs for c in ob.bound_box]
    us = [p.dot(right) for p in pts]
    vs = [p.dot(up) for p in pts]
    ws = [p.dot(back) for p in pts]
    cu, cv = (min(us) + max(us)) / 2, (min(vs) + max(vs)) / 2
    cam.data.ortho_scale = max(max(us) - min(us), max(vs) - min(vs)) * margin
    cam.location = right * cu + up * cv + back * (max(ws) + 400.0)

    sc.render.filepath = path
    bpy.ops.render.render(write_still=True)


def main():
    out = parse_args(sys.argv)
    os.makedirs(out, exist_ok=True)
    reset()

    open_deg = P["jaw_open_deg"]
    fixed = build_fixed_jaw()
    moving = build_moving_jaw()

    export_stl([moving], os.path.join(out, "moving_jaw.stl"))
    export_stl([fixed], os.path.join(out, "fixed_jaw.stl"))

    place_moving_jaw(moving)
    fixed.color = (0.62, 0.65, 0.70, 1.0)
    moving.color = (0.86, 0.45, 0.22, 1.0)

    export_stl([fixed, moving], os.path.join(out, "so101_gripper_assembly.stl"))

    both = [fixed, moving]
    render(os.path.join(out, "so101_gripper.png"),
           (math.radians(66), 0.0, math.radians(38)), both)
    render(os.path.join(out, "so101_gripper_front.png"),
           (math.radians(90), 0.0, 0.0), both)
    render(os.path.join(out, "so101_gripper_side.png"),
           (math.radians(90), 0.0, math.radians(90)), both)

    # the same model with the jaw closed, so the two states can be compared
    P["jaw_open_deg"] = 0.0
    place_moving_jaw(moving)
    render(os.path.join(out, "so101_gripper_closed.png"),
           (math.radians(90), 0.0, 0.0), both)
    P["jaw_open_deg"] = open_deg
    place_moving_jaw(moving)

    bpy.ops.wm.save_as_mainfile(filepath=os.path.abspath(
        os.path.join(out, "so101_gripper.blend")))

    mt = moving.matrix_world @ mathutils.Vector(
        (P["mj_grip_face_x"] - P["mj_grip_face_x"], -P["mj_finger_length"], 0.0))
    print(f"\nBUILD OK  jaw_open_deg={P['jaw_open_deg']}  "
          f"fingertip gap={tip_gap():.1f} mm")
    print(f"  moving fingertip at ({mt.x:.2f}, {mt.y:.2f}, {mt.z:.2f}); "
          f"fixed fingertip z={P['pivot_z'] + P['fixed_finger_length']:.2f}")
    for ob in (fixed, moving):
        d = ob.dimensions
        print(f"  {ob.name:12s} bbox {d.x:7.2f} x {d.y:7.2f} x {d.z:7.2f} mm")


if __name__ == "__main__":
    main()
